package com.example.backendpfe.audit;

public enum AuditAction {

    // CASE MANAGEMENT
    CREATE_CASE,
    RESOLVE_CASE,

    // ACCOUNT
    CREATE_ACCOUNT,
    UPDATE_ACCOUNT,
    DELETE_ACCOUNT,
    RESTORE_ACCOUNT,

    // TRANSACTION
    CREATE_TRANSACTION,
    CREATE_TRANSACTION_FROM_TRANSFER,
    SCORE_TRANSACTION,
    CREATE_FRAUD_ALERT,

    // TRANSFER
    CREATE_TRANSFER,
    APPROVE_TRANSFER,
    REJECT_TRANSFER,

    // ALERT
    UPDATE_ALERT_STATUS,

    // AUTH
    LOGIN
}