package com.example.backendpfe.report;

import com.example.backendpfe.casemanagement.FraudCase;
import com.example.backendpfe.casemanagement.FraudCaseRepository;
import com.example.backendpfe.report.dto.AuditReportResponse;
import com.example.backendpfe.user.User;
import com.example.backendpfe.user.UserRepository;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.time.Instant;
import java.util.List;

@Service
@RequiredArgsConstructor
public class ReportService {

    private final AuditReportRepository auditReportRepository;
    private final FraudCaseRepository fraudCaseRepository;
    private final UserRepository userRepository;

    // 🔥 1. Générer + stocker rapport
    public AuditReport saveAuditReport(Instant startDate, Instant endDate) {

        // 👉 Ici tu peux générer PDF (ou mettre temporairement vide)
        byte[] pdf = generateDummyPdf();

        User currentUser = getCurrentUser();

        AuditReport report = AuditReport.builder()
                .reportReference("REPORT-" + Instant.now().toEpochMilli())
                .fileName("audit-report.pdf")
                .startDate(startDate)
                .endDate(endDate)
                .generatedAt(Instant.now())
                .generatedBy(currentUser)
                .generatedByUsername(currentUser != null ? currentUser.getUsername() : "Unknown")
                .pdfContent(pdf)
                .build();

        return auditReportRepository.save(report);
    }

    // 🔥 2. Liste des rapports
    public Page<AuditReportResponse> getReports(Pageable pageable) {
        return auditReportRepository.findReportsWithoutPdf(pageable);
    }

    // 🔥 3. Télécharger PDF
    public byte[] downloadReport(Long id) {
        AuditReport report = auditReportRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Report not found"));

        return report.getPdfContent();
    }

    // 🔥 UTIL
    private User getCurrentUser() {
        String username = SecurityContextHolder.getContext().getAuthentication().getName();
        return userRepository.findByUsernameAndIsDeletedFalse(username).orElse(null);
    }

    // 🔥 TEMP PDF (tu peux remplacer par iText après)
    private byte[] generateDummyPdf() {
        return "Fake PDF content".getBytes();
    }
    public AuditReport saveCaseReport(Long caseId) {
        FraudCase fraudCase = fraudCaseRepository.findById(caseId)
                .orElseThrow(() -> new RuntimeException("Case not found with id: " + caseId));

        User currentUser = getCurrentUser();

        byte[] pdf = generateCasePdf(fraudCase, currentUser);

        AuditReport saved = auditReportRepository.save(
                AuditReport.builder()
                        .reportReference("REPORT-" + Instant.now().toEpochMilli())
                        .fileName("case-report-" + caseId + ".pdf")
                        .generatedAt(Instant.now())
                        .generatedBy(currentUser)
                        .generatedByUsername(currentUser != null ? currentUser.getUsername() : "Unknown")
                        .caseId(fraudCase.getId())
                        .caseReference("CASE-" + fraudCase.getId())
                        .pdfContent(pdf)
                        .build()
        );

        saved.setReportReference("REPORT-" + saved.getId());
        return auditReportRepository.save(saved);
    }
    private byte[] generateCasePdf(FraudCase c, User currentUser) {
        try {
            ByteArrayOutputStream out = new ByteArrayOutputStream();

            PdfWriter writer = new PdfWriter(out);
            PdfDocument pdf = new PdfDocument(writer);
            Document document = new Document(pdf);

            document.add(new Paragraph("NOVABANK - Case Audit Report").setBold().setFontSize(18));
            document.add(new Paragraph("Generated at: " + Instant.now()));
            document.add(new Paragraph("Generated by: " + (currentUser != null ? currentUser.getUsername() : "Unknown")));
            document.add(new Paragraph(" "));

            document.add(new Paragraph("Case Reference: CASE-" + c.getId()));
            document.add(new Paragraph("Case Status: " + c.getStatus()));
            document.add(new Paragraph("Final Decision: " + (c.getFinalDecision() != null ? c.getFinalDecision() : "-")));
            document.add(new Paragraph("Analyst: " + (c.getOwner() != null ? c.getOwner().getUsername() : "-")));
            document.add(new Paragraph("Opened At: " + c.getOpenedAt()));
            document.add(new Paragraph("Closed At: " + (c.getClosedAt() != null ? c.getClosedAt() : "-")));
            document.add(new Paragraph("Justification: " + (c.getJustification() != null ? c.getJustification() : "-")));

            if (c.getAlert() != null) {
                document.add(new Paragraph(" "));
                document.add(new Paragraph("Linked Alert").setBold());
                document.add(new Paragraph("Alert ID: " + c.getAlert().getId()));
                document.add(new Paragraph("Alert Status: " + c.getAlert().getStatus()));
                document.add(new Paragraph("Reason: " + c.getAlert().getReason()));
            }

            if (c.getAlert() != null && c.getAlert().getTransaction() != null) {
                document.add(new Paragraph(" "));
                document.add(new Paragraph("Linked Transaction").setBold());
                document.add(new Paragraph("Transaction Ref: " + c.getAlert().getTransaction().getTransactionRef()));
                document.add(new Paragraph("Amount: " + c.getAlert().getTransaction().getAmount()));
                document.add(new Paragraph("Risk Level: " + c.getAlert().getTransaction().getRiskLevel()));
                document.add(new Paragraph("Fraud Score: " + c.getAlert().getTransaction().getFraudScore()));
            }

            document.close();
            return out.toByteArray();

        } catch (Exception e) {
            throw new RuntimeException("Error generating case PDF report: " + e.getMessage());
        }
    }
}