package com.example.backendpfe.notification;

public enum NotificationType {
    ACCOUNT_REQUEST_CREATED,
    ACCOUNT_REQUEST_APPROVED,
    ACCOUNT_REQUEST_REJECTED,
    ACCOUNT_CREATED,

    TRANSFER_CREATED,
    TRANSFER_APPROVED,
    TRANSFER_REJECTED,
    TRANSFER_RECEIVED,

    GENERAL_INFO,
    ACCOUNT_INFO,
    SECURITY_ALERT,
    ADMIN_MESSAGE
}
